### ISSUE TITLE
Failes on some sites

### ISSUE THREAD

**Issue by uoosef** [uoosef/bepass#10]
failes on some sites with  Can not connect: tls: first record does not look like a TLS handshake error

**Comment by kaveh-ahangar** [comment]
To better understand the situation and provide a solution, could you please send the relevant logs? Additionally, if you could provide an example URL related to the issue, that would be really helpful. Thank you!

**Comment by DanielcoderX** [comment]
> failes on some sites with Can not connect: tls: first record does not look like a TLS handshake error

The problem is not from core, that's from the DOH.
You can use Seyed's [DOH-Scanner](https://github.com/seyedmahdi4/doh-scanner) to find compatible DOH.

**Comment by uoosef** [comment]
The main issue is fixed "somehow". 

Cloudflare TCP Connect API doesn't allow you to connect to another cloudflare ip, it considers such a connection as a loopback and will drop it. The original author of vless over worker uses public proxies to overcome this issue.

I included some proxies from the original author's work in worker.js, it works now. but the proxy source code is missing, so I will write a proxy for it in the future,

Another method is to not pass the Cloudflare traffic directly through the fragmentation process.
