### ISSUE TITLE
Not Supported Version

### ISSUE THREAD

**Issue by xJuniorProgrammer** [uoosef/bepass#19]
سلام
پیغام خطا میده هنگام اجرا کانفیگ پیش فرض هست اینترنت ثابت شاتل

![2023-08-06_231732](https://github.com/uoosef/bepass/assets/5729722/fb4db86a-7694-41ca-a361-a1707570ad14)

**Comment by uoosef** [comment]
نباید تو بخش پراکسی http و https رو پر کنی، چون خیلیا این اشتباهو میکنن احتمالا پشتیبانی از http و https رو هم اضافه کنم

**Comment by xJuniorProgrammer** [comment]
![2023-08-06_233619](https://github.com/uoosef/bepass/assets/5729722/6cf2d8cd-5cba-40b7-a0c7-792739c44647)
اتفاقی نمیفته چطور بفهمم مشکل از ادرس ها هست یا اصلا داره کار میکنه یا نه؟ سایت گوگل مثلا باز میشه اما youtube نه

**Comment by uoosef** [comment]
سلام دوتا مشکل داری یکی اینکه http پروکسی رو قبلا برنامه ساپورت نمیکرد و من الان اضافش کردم و مشکلو حل کردم، دو اینکه وقتی اینجوری پراکسی خود سیستمو ست میکنی(اون تیک use a proxy server رو بزن لطفا) کوئری های dns از پراکسی رد نمیشن، برای اینکه مشکلت کلا حل بشه دارم به برنامه GUI اضافه میکنم بعلاوه حالت اتوماتیک و tun support، انجام شد همینجا بهت خبر میدم که چک کنی

**Comment by uoosef** [comment]
سلام این مشکل حل شده
