### ISSUE TITLE
Define offline DNS

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [uoosef/bepass#27]
Hi, thanks for your great tool :)  
Please add a feature than we can define offline DNS records like `hosts` file in linux (via json config file)

**Comment by uoosef** [comment]
Hi, i will add this two features
1- a hosts configuration
2- ability to pass DOH through fragmentation

**Comment by uoosef** [comment]
hello its done in the core version i will update plugin version when its ready

**Comment by uoosef** [comment]
plugin version is ready now
