### ISSUE TITLE
Wanna help in Android app?

### ISSUE THREAD

**Issue by metallica1375** [uoosef/bepass#3]

**Comment by uoosef** [comment]
i will release alpha version for android if you can, it has some preblems so it would be very appreciated if you be so kind to reveiw it, i will inform you when it's ready
thanks

**Comment by metallica1375** [comment]
I'd be glad if I can help

**Comment by uoosef** [comment]
hello again, the tun2socks part of android application is done but i need a ui for android that allows user input configurations and save those configs in data folder, can you do this part please ?

**Comment by metallica1375** [comment]
yes, I'm in

**Comment by OmidNejadabbasi** [comment]
@uoosef Hi, where is the android version so I can contribute to it ?
