### ISSUE TITLE
Disable CGO where possible

### ISSUE THREAD

**Issue by markpash** [uoosef/bepass#30]
The included Makefile is used to build the standard cli app and the gui version. The cli app can be compiled statically by setting `CGO_ENABLED=0`. This improves compatibility of the result binary.
The commands for both `build` and `release` targets can be modified like:
`CGO_ENABLED=0 go build -o $(BUILD_DIR)/bepass cmd/cli/main.go`

The GUI needs cgo, so this can't be applied to it.

**Comment by DanielcoderX** [comment]
Hi, Markpash.
I'm gonna try disabling **CGO** as you said.
Thanks.
