### ISSUE TITLE
Slim down cli binary

### ISSUE THREAD

**Issue by markpash** [uoosef/bepass#31]
Doing a local release build, I got a 12M binary. I decided to test compilation without using the cobra and viper dependencies and it came down to 7.7M. I don't know if smaller binaries are important for this project, but since the cli only has a single flag, maybe it's possible to drop that dependency?

I can suggest lighter alternatives:
`github.com/peterbourgon/ff/v3`
`github.com/peterbourgon/ff/v3/ffcli`

**Comment by DanielcoderX** [comment]
Hi, Mark.
I'm (again) going to work on it, currently our main point is working on Android Version and stability but thanks for notifying us.

**Comment by DanielcoderX** [comment]
> Doing a local release build, I got a 12M binary. I decided to test compilation without using the cobra and viper dependencies and it came down to 7.7M. I don't know if smaller binaries are important for this project, but since the cli only has a single flag, maybe it's possible to drop that dependency?
> 
> I can suggest lighter alternatives: `github.com/peterbourgon/ff/v3` `github.com/peterbourgon/ff/v3/ffcli`

Thanks for your great idea, we've moved on
