### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by maanimis** [uoosef/bepass#4]
can you please create a docker-file??

**Comment by JorgeSaicoski** [comment]
Did you try with it?

````
FROM python:3.8

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]
````

**Comment by uoosef** [comment]
this isnt a python app its a golang app and its currently portable enough whats the point in dockerizing it ?
