### ISSUE TITLE
Worker.js

### ISSUE THREAD

**Issue by bhaktadas** [uoosef/bepass#40]
Thank you for your efforts!!
> It also allows you to deploy a free and fast VLESS-like proxy on Cloudflare Workers. Just copy the worker.js to your worker
Where can I find this worker file?

**Comment by DanielcoderX** [comment]
Your welcome.

**Comment by bhaktadas** [comment]
Sorry, it was a question - Where can I find this worker file in your hub?

**Comment by aalaei** [comment]
Where can this worker file be found?
It may have been removed recently, but I don't know the reason.

**Comment by DanielcoderX** [comment]
Hello, Sorry for this confusion.
wiki page updated right now.

**[worker repo](https://github.com/bepass-org/bepass-worker/)**

**[worker.js](https://github.com/bepass-org/bepass-worker/blob/main/dist/worker.js)**

**Comment by aalaei** [comment]
TNX
